version: '3.8'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"  # Exposición pública del proxy
    volumes:
      - ./nginx.conf:/etc/proxy/nginx.conf  # Archivo de configuración del proxy
    networks:
      - app-network
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: init
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - API_URL=http://api:5000  # Enlace hacia el servicio API
    networks:
      - app-network
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/appointments
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appointments
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge

