version: '3.8'

services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
    depends_on:
      - web

  web:
    build: ./web
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "5432:5432"
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "appointments_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
